"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {ArrowRight,Building2,CalendarDays,ChevronRight,Clock3,FileText,Inbox,LayoutDashboard,LockKeyhole,LogOut,Menu,MessageCircle,RefreshCw,Search,ShieldCheck,UserRound,X} from "lucide-react";
import {activeSession,AuthSession,signIn,signOut,supabaseRequest} from "../lib/supabase-rest";
import "./admin.css";

type Lead={id:string;created_at:string;updated_at:string;full_name:string;whatsapp:string;address:string;neighborhood:string;city:string;desired_amount:number;monthly_income:number;status:string;notes:string|null};
const statuses=["novo","em_contato","em_analise","proposta_enviada","aprovado","recusado","concluido"];
const labels:Record<string,string>={novo:"Novo",em_contato:"Em contato",em_analise:"Em análise",proposta_enviada:"Proposta enviada",aprovado:"Aprovado",recusado:"Recusado",concluido:"Concluído"};
const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value);
const date=(value:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));
const localDay=(value:string)=>{const current=new Date(value);return `${current.getFullYear()}-${String(current.getMonth()+1).padStart(2,"0")}-${String(current.getDate()).padStart(2,"0")}`};
const whatsAppLink=(phone:string,name:string)=>{let digits=phone.replace(/\D/g,"");if(digits.length<=11)digits=`55${digits}`;return `https://wa.me/${digits}?text=${encodeURIComponent(`Olá, ${name}! Aqui é da Imper Credi Brasil. Recebemos sua solicitação de crédito e gostaríamos de continuar seu atendimento.`)}`};

function Login({onLogin}:{onLogin:(session:AuthSession)=>void}){
 const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const data=new FormData(e.currentTarget);const email=String(data.get("email")).trim().toLowerCase();const password=String(data.get("password"));try{const session=await signIn(email,password);if(document.activeElement instanceof HTMLElement)document.activeElement.blur();onLogin(session)}catch(err){setError(err instanceof Error?err.message:"Não foi possível entrar.")}finally{setLoading(false)}}
 return <main className="admin-login"><section className="login-brand"><img src="/imper-logo-transparent.png" alt="Imper Credi Brasil"/><p>GESTÃO DE ATENDIMENTOS</p><h1>Controle, agilidade e confiança.</h1><span><ShieldCheck/>Ambiente protegido para a equipe</span></section><form onSubmit={submit}><div className="login-lock"><LockKeyhole/></div><small>ÁREA ADMINISTRATIVA</small><h2>Acesse o painel</h2><p>Entre com o e-mail e a senha autorizados pela empresa.</p><label>E-mail<input name="email" type="email" required autoComplete="email" placeholder="nome@empresa.com.br"/></label><label>Senha<input name="password" type="password" required minLength={6} autoComplete="current-password" placeholder="Digite sua senha"/></label>{error&&<div className="admin-error" role="alert">{error}</div>}<button disabled={loading}>{loading?"Entrando...":"Entrar no painel"}<ArrowRight/></button><div className="secure-note"><ShieldCheck/>Seus dados de acesso são protegidos.</div><a href="/">Voltar para o site</a></form></main>
}

export default function AdminPage(){
 const[session,setSession]=useState<AuthSession|null>(null);const[checking,setChecking]=useState(true);const[loading,setLoading]=useState(false);const[leads,setLeads]=useState<Lead[]>([]);const[selected,setSelected]=useState<Lead|null>(null);const[search,setSearch]=useState("");const[filter,setFilter]=useState("todos");const[dayFilter,setDayFilter]=useState("");const[error,setError]=useState("");const[menu,setMenu]=useState(false);
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);setError("");try{const response=await supabaseRequest("leads?select=*&order=created_at.desc");if(response.status===401)throw new Error("SESSION_EXPIRED");if(response.status===403)throw new Error("Este e-mail ainda não foi autorizado como funcionário.");if(!response.ok)throw new Error("Não foi possível carregar os atendimentos.");setLeads(await response.json() as Lead[])}catch(err){const message=err instanceof Error?err.message:"Erro ao carregar.";if(message==="SESSION_EXPIRED"){await signOut();setSession(null)}else setError(message)}finally{if(!silent)setLoading(false)}},[]);
 useEffect(()=>{activeSession().then(value=>{setSession(value);setChecking(false)})},[]);
 useEffect(()=>{if(!session)return;void load();const interval=window.setInterval(()=>void load(true),12000);return()=>window.clearInterval(interval)},[session,load]);
 const filtered=useMemo(()=>leads.filter(lead=>(filter==="todos"||lead.status===filter)&&(!dayFilter||localDay(lead.created_at)===dayFilter)&&`${lead.full_name} ${lead.whatsapp} ${lead.city}`.toLowerCase().includes(search.toLowerCase())),[leads,search,filter,dayFilter]);
 async function updateStatus(lead:Lead,status:string){const response=await supabaseRequest(`leads?id=eq.${encodeURIComponent(lead.id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({status,updated_at:new Date().toISOString()})});if(!response.ok){setError("Não foi possível atualizar o atendimento.");return}const updated=(await response.json() as Lead[])[0];setLeads(items=>items.map(item=>item.id===updated.id?updated:item));setSelected(updated)}
 async function logout(){await signOut();setSession(null);setLeads([])}
 if(checking)return <main className="admin-loading"><img src="/imper-logo-transparent.png" alt="Imper Credi Brasil"/><p>Preparando seu painel...</p></main>;
 if(!session)return <Login onLogin={setSession}/>;
 const today=leads.filter(lead=>new Date(lead.created_at).toDateString()===new Date().toDateString()).length;
 const inService=leads.filter(lead=>["em_contato","em_analise"].includes(lead.status)).length;
 return <main className="admin-shell">
  <aside className={menu?"open":""}><div className="admin-logo"><img src="/imper-logo-transparent.png" alt="Imper Credi Brasil"/><button onClick={()=>setMenu(false)} aria-label="Fechar menu"><X/></button></div><p className="aside-label">ESPAÇO DA EQUIPE</p><nav><a className="active"><LayoutDashboard/>Atendimentos</a><a href="/"><Building2/>Ver site do cliente</a></nav><div className="aside-support"><ShieldCheck/><span><strong>Ambiente seguro</strong><small>Dados protegidos por acesso</small></span></div><button className="logout" onClick={logout}><LogOut/>Sair da conta</button></aside>
  <section className="admin-main"><header><button className="admin-menu" onClick={()=>setMenu(true)} aria-label="Abrir menu"><Menu/></button><div><small>IMPER CREDI BRASIL</small><h1>Painel de atendimentos</h1></div><div className="live-state"><span/>Atualização automática</div><div className="admin-user"><UserRound/><span><strong>{session.user.email?.split("@")[0]}</strong><small>Administrador</small></span></div></header>
   <div className="admin-content"><div className="content-heading"><div><small>VISÃO GERAL</small><h2>Solicitações de crédito</h2><p>Acompanhe os novos cadastros e continue cada atendimento.</p></div><button onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?"rotating":""}/>{loading?"Atualizando":"Atualizar dados"}</button></div>
    <section className="admin-stats"><article><span><Inbox/></span><div><small>TOTAL DE SOLICITAÇÕES</small><strong>{leads.length}</strong></div></article><article><span><UserRound/></span><div><small>NOVOS LEADS</small><strong>{leads.filter(lead=>lead.status==="novo").length}</strong></div></article><article><span><Clock3/></span><div><small>EM ATENDIMENTO</small><strong>{inService}</strong></div></article><article><span><FileText/></span><div><small>RECEBIDOS HOJE</small><strong>{today}</strong></div></article></section>
    <section className="lead-panel"><div className="panel-heading"><div><small>FILA DE ATENDIMENTO</small><h3>Clientes e solicitações</h3></div><span>{filtered.length} {filtered.length===1?"cadastro":"cadastros"}</span></div><div className="lead-toolbar"><label className="search-field"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente, WhatsApp ou cidade"/></label><label className="date-field"><CalendarDays/><input type="date" value={dayFilter} onChange={e=>setDayFilter(e.target.value)} aria-label="Filtrar por data"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filtrar por status"><option value="todos">Todos os status</option>{statuses.map(status=><option key={status} value={status}>{labels[status]}</option>)}</select>{(dayFilter||filter!=="todos"||search)&&<button className="clear-filters" onClick={()=>{setSearch("");setFilter("todos");setDayFilter("")}} aria-label="Limpar filtros"><X/></button>}</div>{dayFilter&&<div className="day-summary"><CalendarDays/><span><strong>{filtered.length}</strong> {filtered.length===1?"solicitação recebida":"solicitações recebidas"} no dia {new Intl.DateTimeFormat("pt-BR",{dateStyle:"long"}).format(new Date(`${dayFilter}T12:00:00`))}</span></div>}{error&&<div className="admin-error panel-error">{error}</div>}<div className="lead-list">{!loading&&filtered.length===0?<div className="empty"><Inbox/><h3>Nenhum atendimento encontrado</h3><p>As simulações enviadas pelo site aparecerão aqui automaticamente.</p></div>:filtered.map(lead=><button className="lead-row" key={lead.id} onClick={()=>setSelected(lead)}><span className="client"><span className="avatar">{lead.full_name.split(" ").slice(0,2).map(part=>part[0]).join("").toUpperCase()}</span><span><strong>{lead.full_name}</strong><small>{lead.whatsapp} · {lead.city}</small></span></span><strong className="lead-value">{money(lead.desired_amount)}</strong><span className={`status ${lead.status}`}>{labels[lead.status]}</span><small className="lead-date">{date(lead.created_at)}</small><ChevronRight/></button>)}</div></section>
   </div>
  </section>
  {selected&&<div className="detail-backdrop" onClick={()=>setSelected(null)}><aside className="lead-detail" onClick={e=>e.stopPropagation()}><button className="detail-close" onClick={()=>setSelected(null)} aria-label="Fechar"><X/></button><small>DETALHES DO CLIENTE</small><h2>{selected.full_name}</h2><p className="detail-intro">Solicitação recebida pelo formulário do site.</p><a className="whatsapp-action" href={whatsAppLink(selected.whatsapp,selected.full_name.split(" ")[0])} target="_blank" rel="noreferrer"><MessageCircle/>Chamar no WhatsApp<ArrowRight/></a><dl><div><dt>WhatsApp</dt><dd>{selected.whatsapp}</dd></div><div><dt>Endereço</dt><dd>{selected.address}<br/>{selected.neighborhood} — {selected.city}</dd></div><div><dt>Valor desejado</dt><dd>{money(selected.desired_amount)}</dd></div><div><dt>Renda aproximada</dt><dd>{money(selected.monthly_income)}</dd></div><div><dt>Recebido em</dt><dd>{date(selected.created_at)}</dd></div></dl><label className="status-field">Status do atendimento<select value={selected.status} onChange={e=>updateStatus(selected,e.target.value)}>{statuses.map(status=><option key={status} value={status}>{labels[status]}</option>)}</select></label></aside></div>}
 </main>
}
