"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {ArrowRight,Building2,ChevronRight,Clock3,Eye,FileText,LayoutDashboard,LockKeyhole,LogOut,Menu,MessageCircle,Search,ShieldCheck,UserRound,X} from "lucide-react";
import {activeSession,AuthSession,signIn,signOut,supabaseRequest} from "../lib/supabase-rest";
import "./admin.css";

type Lead={id:string;created_at:string;updated_at:string;full_name:string;whatsapp:string;address:string;neighborhood:string;city:string;desired_amount:number;monthly_income:number;status:string;notes:string|null};
const statuses=["novo","em_contato","em_analise","proposta_enviada","aprovado","recusado","concluido"];
const labels:Record<string,string>={novo:"Novo",em_contato:"Em contato",em_analise:"Em análise",proposta_enviada:"Proposta enviada",aprovado:"Aprovado",recusado:"Recusado",concluido:"Concluído"};
const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value);
const date=(value:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));
const whatsAppLink=(phone:string,name:string)=>{let digits=phone.replace(/\D/g,"");if(digits.length<=11)digits=`55${digits}`;return `https://wa.me/${digits}?text=${encodeURIComponent(`Olá, ${name}! Aqui é da Imper Credi Brasil. Recebemos sua solicitação de crédito e gostaríamos de continuar seu atendimento.`)}`};
const demoLeads:Lead[]=[
 {id:"demo-1",created_at:new Date().toISOString(),updated_at:new Date().toISOString(),full_name:"Mariana Costa",whatsapp:"(48) 99988-1111",address:"Av. Central, 245",neighborhood:"Centro",city:"Florianópolis",desired_amount:50000,monthly_income:6500,status:"novo",notes:null},
 {id:"demo-2",created_at:new Date(Date.now()-86400000).toISOString(),updated_at:new Date().toISOString(),full_name:"Carlos Eduardo Lima",whatsapp:"(48) 99876-4321",address:"Rua das Palmeiras, 80",neighborhood:"Trindade",city:"Florianópolis",desired_amount:120000,monthly_income:12000,status:"em_contato",notes:null},
 {id:"demo-3",created_at:new Date(Date.now()-172800000).toISOString(),updated_at:new Date().toISOString(),full_name:"Juliana Martins",whatsapp:"(48) 98888-1111",address:"Rua São José, 310",neighborhood:"Kobrasol",city:"São José",desired_amount:35000,monthly_income:4800,status:"em_analise",notes:null}
];

function Login({onLogin,onDemo}:{onLogin:(session:AuthSession)=>void;onDemo:()=>void}){
 const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const data=new FormData(e.currentTarget);const email=String(data.get("email")).toLowerCase();const password=String(data.get("password"));if(email==="admin@impercredi.com.br"&&password==="Imper@2026"){onDemo();setLoading(false);return}try{onLogin(await signIn(email,password))}catch(err){setError(err instanceof Error?err.message:"Não foi possível entrar.")}finally{setLoading(false)}}
 return <main className="admin-login"><section className="login-brand"><img src="/imper-logo-transparent.png" alt="Imper Credi Brasil"/><p>GESTÃO DE ATENDIMENTOS</p><h1>Crédito com organização e clareza.</h1><span><ShieldCheck/>Acesso restrito à equipe autorizada</span></section><form onSubmit={submit}><div className="login-lock"><LockKeyhole/></div><small>ÁREA ADMINISTRATIVA</small><h2>Entre na sua conta</h2><p>Use o Gmail e a senha cadastrados pela empresa.</p><div className="demo-access"><strong>ACESSO DE DEMONSTRAÇÃO</strong><span>Gmail: admin@impercredi.com.br</span><span>Senha: Imper@2026</span></div><label>Gmail<input name="email" type="email" required autoComplete="email" placeholder="seuemail@gmail.com"/></label><label>Senha<input name="password" type="password" required minLength={6} autoComplete="current-password" placeholder="Digite sua senha"/></label>{error&&<div className="admin-error" role="alert">{error}</div>}<button disabled={loading}>{loading?"Entrando...":"Entrar no painel"}<ArrowRight/></button><a href="/">Voltar para o site</a></form></main>
}

export default function AdminPage(){
 const[session,setSession]=useState<AuthSession|null>(null);const[demo,setDemo]=useState(false);const[checking,setChecking]=useState(true);const[leads,setLeads]=useState<Lead[]>([]);const[selected,setSelected]=useState<Lead|null>(null);const[search,setSearch]=useState("");const[filter,setFilter]=useState("todos");const[error,setError]=useState("");const[menu,setMenu]=useState(false);
 async function load(){setError("");try{const response=await supabaseRequest("leads?select=*&order=created_at.desc");if(response.status===401)throw new Error("SESSION_EXPIRED");if(response.status===403)throw new Error("Seu Gmail ainda não foi autorizado como funcionário.");if(!response.ok)throw new Error("Não foi possível carregar os atendimentos.");setLeads(await response.json() as Lead[])}catch(err){const message=err instanceof Error?err.message:"Erro ao carregar.";if(message==="SESSION_EXPIRED"){await signOut();setSession(null)}else setError(message)}}
 useEffect(()=>{activeSession().then(value=>{setSession(value);setChecking(false);if(value)setTimeout(()=>load(),0)})},[]);
 const filtered=useMemo(()=>leads.filter(lead=>(filter==="todos"||lead.status===filter)&&`${lead.full_name} ${lead.whatsapp} ${lead.city}`.toLowerCase().includes(search.toLowerCase())),[leads,search,filter]);
 async function updateStatus(lead:Lead,status:string){if(demo){const updated={...lead,status,updated_at:new Date().toISOString()};setLeads(items=>items.map(item=>item.id===updated.id?updated:item));setSelected(updated);return}const response=await supabaseRequest(`leads?id=eq.${encodeURIComponent(lead.id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({status,updated_at:new Date().toISOString()})});if(!response.ok){setError("Não foi possível atualizar o atendimento.");return}const updated=(await response.json() as Lead[])[0];setLeads(items=>items.map(item=>item.id===updated.id?updated:item));setSelected(updated)}
 async function logout(){if(!demo)await signOut();setDemo(false);setSession(null);setLeads([])}
 if(checking)return <main className="admin-loading"><img src="/imper-logo-transparent.png" alt="Imper Credi Brasil"/><p>Carregando painel...</p></main>;
 if(!session)return <Login onLogin={value=>{setSession(value);setTimeout(()=>load(),0)}} onDemo={()=>{setDemo(true);setSession({access_token:"demo",refresh_token:"demo",expires_in:3600,user:{id:"demo",email:"admin@impercredi.com.br"}});setLeads(demoLeads)}}/>;
 const today=leads.filter(lead=>new Date(lead.created_at).toDateString()===new Date().toDateString()).length;
 return <main className="admin-shell">
  <aside className={menu?"open":""}><div className="admin-logo"><img src="/imper-logo-transparent.png" alt="Imper Credi Brasil"/><button onClick={()=>setMenu(false)} aria-label="Fechar menu"><X/></button></div><nav><a className="active"><LayoutDashboard/>Atendimentos</a><a href="/"><Building2/>Ver site</a></nav><button className="logout" onClick={logout}><LogOut/>Sair da conta</button></aside>
  <section className="admin-main"><header><button className="admin-menu" onClick={()=>setMenu(true)} aria-label="Abrir menu"><Menu/></button><div><small>IMPER CREDI BRASIL {demo&&"· DEMONSTRAÇÃO"}</small><h1>Painel de atendimentos</h1></div><div className="admin-user"><UserRound/><span><strong>{session.user.email?.split("@")[0]}</strong><small>{demo?"Acesso fictício":"Funcionário"}</small></span></div></header>
   <div className="admin-content"><section className="admin-stats"><article><span><UserRound/></span><small>NOVOS LEADS</small><strong>{leads.filter(lead=>lead.status==="novo").length}</strong></article><article><span><Clock3/></span><small>EM ATENDIMENTO</small><strong>{leads.filter(lead=>["em_contato","em_analise"].includes(lead.status)).length}</strong></article><article><span><FileText/></span><small>RECEBIDOS HOJE</small><strong>{today}</strong></article></section>
    <section className="lead-panel"><div className="lead-toolbar"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente, WhatsApp ou cidade"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filtrar por status"><option value="todos">Todos os status</option>{statuses.map(status=><option key={status} value={status}>{labels[status]}</option>)}</select></div>{error&&<div className="admin-error">{error}</div>}<div className="lead-list">{filtered.length===0?<div className="empty"><Eye/><h3>Nenhum atendimento encontrado</h3><p>Os novos pedidos enviados pelo site aparecerão aqui.</p></div>:filtered.map(lead=><button className="lead-row" key={lead.id} onClick={()=>setSelected(lead)}><span className="client"><span className="avatar">{lead.full_name.slice(0,2).toUpperCase()}</span><span><strong>{lead.full_name}</strong><small>{lead.whatsapp} · {lead.city}</small></span></span><strong>{money(lead.desired_amount)}</strong><span className={`status ${lead.status}`}>{labels[lead.status]}</span><small>{date(lead.created_at)}</small><ChevronRight/></button>)}</div></section>
   </div>
  </section>
  {selected&&<div className="detail-backdrop" onClick={()=>setSelected(null)}><aside className="lead-detail" onClick={e=>e.stopPropagation()}><button className="detail-close" onClick={()=>setSelected(null)} aria-label="Fechar"><X/></button><small>DETALHES DO CLIENTE</small><h2>{selected.full_name}</h2><a className="whatsapp-action" href={whatsAppLink(selected.whatsapp,selected.full_name.split(" ")[0])} target="_blank" rel="noreferrer"><MessageCircle/>Chamar no WhatsApp<ArrowRight/></a><dl><div><dt>WhatsApp</dt><dd>{selected.whatsapp}</dd></div><div><dt>Endereço</dt><dd>{selected.address}<br/>{selected.neighborhood} — {selected.city}</dd></div><div><dt>Valor desejado</dt><dd>{money(selected.desired_amount)}</dd></div><div><dt>Renda aproximada</dt><dd>{money(selected.monthly_income)}</dd></div><div><dt>Recebido em</dt><dd>{date(selected.created_at)}</dd></div></dl><label className="status-field">Status do atendimento<select value={selected.status} onChange={e=>updateStatus(selected,e.target.value)}>{statuses.map(status=><option key={status} value={status}>{labels[status]}</option>)}</select></label></aside></div>}
 </main>
}
