"use client";
import {useState} from "react";
import {ArrowRight,Check,ChevronDown,Clock3,FileText,Headphones,Menu,MessageCircle,ShieldCheck,UserRound,X} from "lucide-react";

const steps=[[FileText,"Preencha a simulação","Informe os dados essenciais para entendermos o crédito que você procura."],[Headphones,"Converse com um especialista","Nossa equipe entra em contato para ouvir, orientar e esclarecer suas dúvidas."],[Check,"Conheça sua proposta","Você recebe uma solução analisada para o seu perfil, com os próximos passos bem explicados."]] as const;
const faqs=[["A simulação tem algum custo?","Não. A simulação é gratuita e não gera obrigação de contratação."],["Como receberei o contato?","Um especialista da Imper Credi Brasil falará com você pelo WhatsApp informado."],["Quais dados preciso informar?","Nesta etapa pedimos apenas nome, WhatsApp, valor desejado e renda aproximada."]];
function Brand(){return <span className="brand"><span className="brand-monogram">IC</span><span className="brand-name"><strong>Imper Credi</strong><small>Brasil</small></span></span>}

export default function Home(){
 const[menu,setMenu]=useState(false),[open,setOpen]=useState<number|null>(0),[sent,setSent]=useState(false);
 return <main>
  <header className="site-header"><a href="#inicio"><Brand/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label={menu?"Fechar menu":"Abrir menu"}>{menu?<X strokeWidth={1.5}/>:<Menu strokeWidth={1.5}/>}</button><nav className={menu?"nav open":"nav"}>{[["Início","#inicio"],["Como funciona","#como-funciona"],["Quem somos","#quem-somos"],["Dúvidas","#duvidas"]].map(([l,h])=><a key={h} href={h} onClick={()=>setMenu(false)}>{l}</a>)}<a className="nav-cta" href="#simulacao">Simular crédito</a></nav></header>
  <section className="hero" id="inicio"><div className="hero-copy"><p className="kicker">Consultoria de crédito · Atendimento nacional</p><h1>Crédito com <em>clareza</em> para decisões mais seguras.</h1><p className="hero-text">Uma conversa humana, uma análise cuidadosa e uma proposta explicada de verdade. A Imper Credi Brasil acompanha você em cada etapa.</p><div className="hero-actions"><a className="button primary-button" href="#simulacao">Iniciar simulação <ArrowRight size={18}/></a><a className="text-link" href="#como-funciona">Entenda o processo</a></div><div className="hero-proof"><ShieldCheck strokeWidth={1.4}/><p><strong>Atendimento responsável</strong><span>Seus dados são utilizados apenas para dar andamento à sua solicitação.</span></p></div></div>
   <form className="simulation-card" id="simulacao" onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success"><Check/><p className="form-index">Solicitação registrada</p><h2>Recebemos sua simulação.</h2><p>Esta é a experiência visual do Front-end. A conexão com o atendimento real será feita na etapa do Supabase.</p><button type="button" onClick={()=>setSent(false)}>Fazer outra simulação</button></div>:<><div className="form-heading"><p className="form-index">01 — Primeiro contato</p><h2>Conte-nos o que você precisa.</h2><p>Leva menos de dois minutos.</p></div><label>Nome completo<input name="name" placeholder="Como podemos chamar você?" required/></label><label>WhatsApp<input name="phone" inputMode="tel" placeholder="(00) 00000-0000" required/></label><div className="field-row"><label>Valor desejado<input name="amount" placeholder="R$ 5.000,00" required/></label><label>Renda aproximada<input name="income" placeholder="R$ 3.000,00" required/></label></div><label className="consent"><input type="checkbox" required/><span>Autorizo o contato da equipe para dar continuidade a esta solicitação.</span></label><button className="button form-button">Solicitar atendimento <ArrowRight size={18}/></button></>}</form>
  </section>
  <section className="service-bar"><span><UserRound/><small>01</small> Atendimento humano</span><span><Clock3/><small>02</small> Processo objetivo</span><span><MessageCircle/><small>03</small> Retorno pelo WhatsApp</span></section>
  <section className="section process" id="como-funciona"><div className="section-intro"><p className="kicker">Como funciona</p><h2>Um processo simples.<br/><em>Uma orientação completa.</em></h2></div><div className="process-list">{steps.map(([Icon,t,d],i)=><article className="process-item" key={t}><span>0{i+1}</span><Icon strokeWidth={1.35}/><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
  <section className="section about" id="quem-somos"><div className="about-image"><img src="/equipe-imper-credi.jpeg" alt="Representante da Imper Credi Brasil"/></div><div className="about-copy"><p className="kicker">Imper Credi Brasil</p><h2>Confiança se constrói com presença.</h2><p>Nosso trabalho começa antes da proposta. Ouvimos sua necessidade, explicamos as possibilidades com clareza e acompanhamos cada etapa com atenção.</p><blockquote>“Crédito não deve ser apenas uma operação. Deve ser uma decisão bem orientada.”</blockquote><ul><li><Check/>Conversa direta com um especialista</li><li><Check/>Informações claras, sem complicação</li><li><Check/>Soluções avaliadas para cada perfil</li></ul></div></section>
  <section className="section faq" id="duvidas"><div className="faq-heading"><p className="kicker">Dúvidas frequentes</p><h2>Informação também é parte do atendimento.</h2></div><div className="faq-list">{faqs.map(([q,a],i)=><article className={open===i?"faq-item active":"faq-item"} key={q}><button onClick={()=>setOpen(open===i?null:i)}><span><small>0{i+1}</small>{q}</span><ChevronDown/></button><div className="faq-answer"><p>{a}</p></div></article>)}</div></section>
  <section className="contact"><p className="kicker">Seu próximo passo</p><h2>Vamos conversar sobre o crédito que você procura?</h2><a className="button primary-button" href="#simulacao">Fazer minha simulação <ArrowRight size={18}/></a></section>
  <footer><Brand/><p>Atendimento humano. Decisões com clareza.</p><nav><a href="#como-funciona">Como funciona</a><a href="#quem-somos">Quem somos</a><a href="#duvidas">Dúvidas</a></nav><small>© 2026 Imper Credi Brasil. Todos os direitos reservados.</small></footer>
 </main>
}
