"use client";
import { useState } from "react";
import { ArrowRight, Check, ChevronDown, FileCheck2, Headphones, Menu, MessageCircle, ShieldCheck, Sparkles, X } from "lucide-react";

const steps = [[FileCheck2,"Faça sua simulação","Preencha os dados essenciais. É rápido, simples e sem compromisso."],[Headphones,"Fale com nossa equipe","Um especialista entra em contato para entender o que você precisa."],[Check,"Receba sua proposta","Apresentamos uma solução personalizada para o seu momento."]] as const;
const faqs = [["A simulação tem algum custo?","Não. A simulação é gratuita e não gera nenhuma obrigação de contratação."],["Quanto tempo leva para receber o contato?","Após o envio, sua solicitação entra na fila da equipe. Um especialista fará o contato pelo WhatsApp informado."],["Meus dados ficam protegidos?","Sim. Solicitamos apenas as informações necessárias para iniciar o atendimento e tratamos os dados com responsabilidade."]];

function Brand(){return <span className="brand-ring"><span className="brand-imper">Imper</span><span className="brand-credi">Credi</span><span className="brand-brasil">Brasil</span></span>}

export default function Home(){
 const [menuOpen,setMenuOpen]=useState(false); const [openFaq,setOpenFaq]=useState<number|null>(0); const [sent,setSent]=useState(false);
 return <main>
  <header className="site-header"><a href="#inicio" aria-label="Imper Credi Brasil - início"><Brand/></a><button className="menu-toggle" onClick={()=>setMenuOpen(!menuOpen)} aria-label={menuOpen?"Fechar menu":"Abrir menu"}>{menuOpen?<X/>:<Menu/>}</button><nav className={menuOpen?"nav open":"nav"}>{[["Início","#inicio"],["Como funciona","#como-funciona"],["Quem somos","#quem-somos"],["Dúvidas","#duvidas"],["Contato","#contato"]].map(([label,href])=><a key={href} href={href} onClick={()=>setMenuOpen(false)}>{label}</a>)}</nav></header>
  <section className="hero" id="inicio"><div className="orb red"/><div className="orb blue"/><div className="skyline"/><div className="hero-copy"><p className="eyebrow"><Sparkles size={15}/> Imper Credi Brasil</p><h1>Crédito que <span>confia em você.</span></h1><div className="accent-line"/><p className="hero-text">Faça sua simulação e receba um atendimento personalizado da nossa equipe.</p><a className="button red-button" href="#simulacao">Simular crédito <ArrowRight size={19}/></a><p className="privacy"><ShieldCheck size={18}/> Seus dados tratados com segurança.</p></div>
   <form className="simulation-card" id="simulacao" onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success" role="status"><span><Check/></span><h2>Simulação recebida</h2><p>Esta é a prévia do Front-end. Na próxima etapa, conectaremos o envio ao atendimento real.</p><button type="button" onClick={()=>setSent(false)}>Fazer outra simulação</button></div>:<><div className="card-heading"><p>Atendimento personalizado</p><h2>Simule seu crédito</h2></div><label>Nome<input name="name" placeholder="Seu nome completo" required/></label><label>WhatsApp<input name="phone" inputMode="tel" placeholder="(00) 00000-0000" required/></label><div className="field-row"><label>Valor desejado<input name="amount" inputMode="decimal" placeholder="R$ 5.000,00" required/></label><label>Renda aproximada<input name="income" inputMode="decimal" placeholder="R$ 3.000,00" required/></label></div><label className="consent"><input type="checkbox" required/><span>Concordo com o uso dos meus dados para receber o atendimento solicitado.</span></label><button className="button gold-button" type="submit">Enviar simulação <ArrowRight size={19}/></button></>}</form>
  </section>
  <section className="trust-strip"><span><Headphones/> Atendimento humano</span><span><ShieldCheck/> Processo seguro</span><span><MessageCircle/> Retorno pelo WhatsApp</span></section>
  <section className="section how" id="como-funciona"><div className="section-heading"><p className="eyebrow">Simples e transparente</p><h2>Como funciona</h2><p>Você faz a simulação em poucos minutos. Nossa equipe cuida do restante com atenção.</p></div><div className="steps-grid">{steps.map(([Icon,title,text],i)=><article className="step-card" key={title}><b>0{i+1}</b><span className="step-icon"><Icon/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="section about" id="quem-somos"><div className="about-image"><img src="/equipe-imper-credi.jpeg" alt="Representante da Imper Credi Brasil"/><div>Imper Credi Brasil<br/><strong>Confia em você</strong></div></div><div className="about-copy"><p className="eyebrow">Atendimento que aproxima</p><h2>Crédito começa com uma boa conversa.</h2><p>A Imper Credi Brasil nasceu para tornar o acesso ao crédito mais humano, claro e próximo. Cada solicitação é acompanhada por uma equipe preparada para orientar você.</p><ul><li><Check/> Atendimento personalizado</li><li><Check/> Explicações claras em cada etapa</li><li><Check/> Soluções pensadas para cada perfil</li></ul></div></section>
  <section className="section faq" id="duvidas"><div className="section-heading left"><p className="eyebrow">Dúvidas frequentes</p><h2>Antes de simular, saiba mais.</h2></div><div className="faq-list">{faqs.map(([q,a],i)=><article className={openFaq===i?"faq-item active":"faq-item"} key={q}><button onClick={()=>setOpenFaq(openFaq===i?null:i)}>{q}<ChevronDown/></button><div className="faq-answer"><p>{a}</p></div></article>)}</div></section>
  <section className="contact" id="contato"><p className="eyebrow">Pronto para começar?</p><h2>Faça sua simulação.</h2><p>Nossa equipe entrará em contato para explicar os próximos passos.</p><a className="button red-button" href="#simulacao">Simular agora <ArrowRight size={19}/></a></section>
  <footer><div className="footer-brand">Imper <span>Credi</span> <small>Brasil</small></div><p>Atendimento humano, crédito com confiança.</p><nav><a href="#como-funciona">Como funciona</a><a href="#duvidas">Dúvidas</a><a href="#contato">Contato</a></nav><small>© 2026 Imper Credi Brasil. Todos os direitos reservados.</small></footer>
 </main>
}
