"use client";
import {useState} from "react";
import {ArrowDown,ArrowRight,BriefcaseBusiness,Building2,Camera,Check,ChevronDown,Clock3,FileText,Landmark,Menu,MessageCircle,ShieldCheck,UserRound,X} from "lucide-react";

const benefits=[["01","Atendimento individual","Uma conversa clara para entender seu momento e suas necessidades."],["02","Análise responsável","Cada solicitação é avaliada com atenção, segurança e transparência."],["03","Solução personalizada","Propostas construídas de acordo com o perfil de cada cliente."]];
const solutions=[[UserRound,"Crédito pessoal","Soluções para organizar planos, projetos e imprevistos com tranquilidade."],[Landmark,"Crédito com garantia","Condições diferenciadas para quem busca maior prazo e flexibilidade."],[BriefcaseBusiness,"Crédito empresarial","Capital para investir, organizar o caixa e apoiar o crescimento do negócio."]] as const;
const faqs=[["A simulação tem algum custo?","Não. A simulação é gratuita e não gera obrigação de contratação."],["Como receberei o contato?","Um especialista falará com você pelo WhatsApp informado."],["Quanto tempo demora a análise?","O prazo depende do perfil e da modalidade escolhida. A equipe explica cada etapa durante o atendimento."]];
function Brand(){return <span className="brand"><img src="/imper-logo.png" alt="Imper Credi Brasil"/></span>}

export default function Home(){
 const[menu,setMenu]=useState(false),[open,setOpen]=useState<number|null>(0),[sent,setSent]=useState(false);
 return <main>
  <header className="site-header"><a href="#inicio"><Brand/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label={menu?"Fechar menu":"Abrir menu"}>{menu?<X/>:<Menu/>}</button><nav className={menu?"nav open":"nav"}>{[["Soluções","#solucoes"],["Como funciona","#processo"],["Sobre","#sobre"],["Contato","#contato"]].map(([l,h])=><a key={h} href={h} onClick={()=>setMenu(false)}>{l}</a>)}</nav><a className="header-cta" href="#simulacao">Simular crédito</a></header>

  <section className="hero" id="inicio"><p className="eyebrow">CONSULTORIA DE CRÉDITO · ATENDIMENTO NACIONAL</p><h1>Crédito com clareza.<br/><em>Confiança em cada escolha.</em></h1><p>Atendimento próximo, análise responsável e soluções pensadas para o seu momento.</p><a className="button gold-button" href="#simulacao">Fazer uma simulação <ArrowRight size={17}/></a><a className="discover" href="#solucoes">CONHEÇA A IMPER CREDI <ArrowDown size={15}/></a></section>

  <section className="benefits">{benefits.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</section>

  <section className="section solutions" id="solucoes"><div className="section-heading"><p className="eyebrow">SOLUÇÕES EM DESTAQUE</p><h2>Escolha o crédito que combina com seus planos.</h2><p>Conheça algumas das modalidades que a nossa equipe pode avaliar com você.</p></div><div className="solution-grid">{solutions.map(([Icon,t,d],i)=><article key={t}><span className="card-number">0{i+1}</span><Icon strokeWidth={1.35}/><h3>{t}</h3><p>{d}</p><a href="#simulacao">Simular agora <ArrowRight size={15}/></a></article>)}</div></section>

  <section className="section process" id="processo"><div><p className="eyebrow">COMO FUNCIONA</p><h2>Simples para você.<br/><em>Cuidadoso em cada etapa.</em></h2></div><div className="process-list"><article><span>01</span><FileText/><div><h3>Envie sua simulação</h3><p>Preencha seus dados e conte qual valor você procura.</p></div></article><article><span>02</span><MessageCircle/><div><h3>Fale com um especialista</h3><p>Nossa equipe entra em contato para entender melhor sua necessidade.</p></div></article><article><span>03</span><Check/><div><h3>Receba a orientação</h3><p>Explicamos as possibilidades e os próximos passos com transparência.</p></div></article></div></section>

  <section className="section simulation" id="simulacao"><div className="simulation-copy"><p className="eyebrow">SIMULAÇÃO DE CRÉDITO</p><h2>Conte o que você precisa.</h2><p>Preencha as informações iniciais. Um especialista continuará o atendimento pelo WhatsApp.</p><div><ShieldCheck/><span><strong>Dados tratados com responsabilidade</strong><small>Utilizados somente para o atendimento solicitado.</small></span></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success"><Check/><h3>Simulação recebida.</h3><p>Em breve, nossa equipe entrará em contato para explicar os próximos passos.</p><button type="button" onClick={()=>setSent(false)}>Fazer outra simulação</button></div>:<><label>Nome completo<input required placeholder="Digite seu nome"/></label><label>WhatsApp<input required inputMode="tel" placeholder="(00) 00000-0000"/></label><div className="field-row"><label>Valor desejado<input required placeholder="R$ 10.000,00"/></label><label>Renda aproximada<input required placeholder="R$ 4.000,00"/></label></div><label className="consent"><input type="checkbox" required/><span>Autorizo o contato da equipe para continuar esta solicitação.</span></label><button className="button dark-button">Solicitar atendimento <ArrowRight size={17}/></button></>}</form></section>

  <section className="section about" id="sobre"><div><p className="eyebrow">SOBRE A IMPER CREDI</p><h2>Atendimento próximo.<br/>Decisões com segurança.</h2><p>A Imper Credi Brasil nasceu para tornar o acesso ao crédito mais claro e humano. Cada atendimento começa com uma conversa e segue com orientação em todas as etapas.</p><ul><li><Check/>Atendimento personalizado</li><li><Check/>Explicações claras</li><li><Check/>Soluções para cada perfil</li></ul></div><blockquote>“Mais do que encontrar crédito, ajudamos você a entender cada escolha.”</blockquote></section>

  <section className="section faq"><div className="section-heading left"><p className="eyebrow">DÚVIDAS FREQUENTES</p><h2>Antes de simular, saiba mais.</h2></div><div className="faq-list">{faqs.map(([q,a],i)=><article className={open===i?"active":""} key={q}><button onClick={()=>setOpen(open===i?null:i)}><span><small>0{i+1}</small>{q}</span><ChevronDown/></button><div><p>{a}</p></div></article>)}</div></section>

  <section className="section contact" id="contato"><div className="section-heading left"><p className="eyebrow">CONTATO</p><h2>Fale com a Imper Credi.</h2></div><div className="contact-grid"><a href="#simulacao"><MessageCircle/><span><small>ATENDIMENTO</small><strong>WhatsApp</strong><em>Dúvidas e informações</em></span></a><a href="https://www.instagram.com/impercredibrasil" target="_blank" rel="noreferrer"><Camera/><span><small>NOVIDADES</small><strong>Instagram</strong><em>@impercredibrasil</em></span></a><article><Building2/><span><small>UNIDADE FICTÍCIA</small><strong>Florianópolis</strong><em>Santa Catarina · Brasil</em></span></article><article><Clock3/><span><small>ATENDIMENTO</small><strong>Horários</strong><em>Seg–sex · 9h às 18h</em></span></article></div></section>

  <footer><Brand/><span>Crédito com clareza e confiança.</span><nav><a href="#solucoes">Soluções</a><a href="#sobre">Sobre</a><a href="#contato">Contato</a></nav><small>© 2026 Imper Credi Brasil</small></footer>
 </main>
}
